namespace AIRecruiter.Application.DTOs.Candidates;

public record CandidateProfileDto(
    int Id,
    string FullName,
    string? Headline,
    string? Summary,
    string? Education,
    int? GraduationYear,
    string? ExperienceSummary,
    int? TotalExperienceYears,
    string? City,
    string? State,
    string? Locality,
    string DisplayLocation,
    decimal? CurrentSalary,
    decimal? ExpectedSalary,
    string? SkillsCsv,
    string? Phone,
    string? LinkedInUrl,
    string? GithubUrl,
    string? PortfolioUrl,
    string? ResumeOriginalFileName,
    long? ResumeSizeBytes,
    DateTime? ResumeUploadedAt,
    string? AvatarUrl);

public record UpsertCandidateProfileRequest(
    string? Headline,
    string? Summary,
    string? Education,
    int? GraduationYear,
    string? ExperienceSummary,
    int? TotalExperienceYears,
    string? City,
    string? State,
    string? Locality,
    decimal? CurrentSalary,
    decimal? ExpectedSalary,
    string? SkillsCsv,
    string? Phone,
    string? LinkedInUrl,
    string? GithubUrl,
    string? PortfolioUrl);
